### ISSUE TITLE
[warn] 3488#3488 Nginx Nextcloud 27

### ISSUE THREAD

**Issue by JoroMarin** [emanuelpina/emanuelpina.pt#39]
Hi Emanuel,
Just perfect tutorial regarding installing latest Nextcloud 27 Installation on Debian
Just one warning when test page on nginx
---------------------------------------------------------------------------------------------
user1@server1:[/etc/nginx/sites-available]$ sudo nginx -t
2023/07/26 10:18:42 [warn] 3701#3701: duplicate extension "js", content type: "text/javascript", previous content type: "application/javascript" in /etc/nginx/sites-enabled/nextcloud:94
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
----------------------------------------------------------------------------------------------
Any suggestion how to fix this ?

**Comment by emanuelpina** [comment]
I'm aware of this warning. Didn't had an answer at the time I updated the tutorial.

That warning is due as result of this line on Nginx configuration, as [documented](https://docs.nextcloud.com/server/27/admin_manual/installation/nginx.html#nextcloud-in-the-webroot-of-nginx) by Nextcloud:

```
gzip_types application/atom+xml text/javascript application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject application/wasm application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/bmp image/svg+xml image/x-icon text/cache-manifest text/css text/plain text/vcard text/vnd.rim.location.xloc text/vtt text/x-component text/x-cross-domain-policy;
```

More precisely because of the occurrence at the same time of `text/javascript` and `application/javascript`.

After [further research](https://stackoverflow.com/questions/21098865/text-javascript-vs-application-javascript), looks like `application/javascript` is obsolete and the standard is now `text/javascript`.

The include of both on the above expression seems to be valid to ensure backward compatibility. So, seems that warning can be safely dismissed.

**Comment by JoroMarin** [comment]
I'm able to fix with removing 'js' from:

include mime.types;
    types {
        text/javascript  mjs;
    }

After this no more warning and everything works as expected

**Comment by emanuelpina** [comment]
> I'm able to fix with removing 'js' from:
> 
> include mime.types; types { text/javascript mjs; }

Surprised this hasn't broken your installation. I think it's better to just ignore the warning.
